import React, { useEffect, useState } from 'react';
import { ChevronDown, Megaphone, Plus } from 'lucide-react';
import toast from 'react-hot-toast';
import { supabase } from '../../../services/supabase';
import { Modal } from '../../common/Modal';
import { useAuthStore } from '../../../store/authStore';

export const CampaignPanel: React.FC = () => {
  const profile = useAuthStore(s => s.profile); const canCreate = profile?.role === 'admin' || profile?.role === 'manager' || profile?.employment_level === 'Leader';
  const [open, setOpen] = useState(true), [create, setCreate] = useState(false), [campaigns, setCampaigns] = useState<any[]>([]), [people, setPeople] = useState<any[]>([]);
  const [name, setName] = useState(''), [objective, setObjective] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState(''), [budget, setBudget] = useState(''), [channels, setChannels] = useState<string[]>([]), [lead, setLead] = useState(''), [status, setStatus] = useState('draft');
  const load = async () => { const [c, u] = await Promise.all([supabase.from('campaigns').select('*, lead:lead_id(name)').order('created_at', { ascending: false }), supabase.from('users').select('id,name,department_id').eq('is_active', true)]); setCampaigns(c.data || []); setPeople((u.data || []).filter((p:any) => profile?.role === 'admin' || profile?.role === 'manager' || p.department_id === profile?.department_id)); };
  useEffect(() => { load(); }, []);
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!name) return; const { error } = await supabase.from('campaigns').insert({ name, objective, start_date:start||null, end_date:end||null, budget:budget ? Number(budget) : null, channels, lead_id: lead ? Number(lead) : null, status, department_id: profile?.department_id || null, workspace_id:'9000eae0-528c-47a2-b6f3-eba019d4edca', created_by:profile?.id || null }); if (error) return toast.error('Không thể tạo chiến dịch'); setCreate(false); setName(''); setObjective(''); setChannels([]); load(); toast.success('Đã tạo chiến dịch'); };
  return <section className="card-hub rounded-xl border border-gray-200 dark:border-slate-700"><div className="flex items-center justify-between p-4"><button onClick={()=>setOpen(!open)} className="flex items-center gap-2 font-bold"><ChevronDown className={`transition-transform ${open ? '' : '-rotate-90'}`} size={18}/><Megaphone className="text-primary" size={18}/> Campaigns <span className="text-xs font-medium text-gray-500">{campaigns.length}</span></button>{canCreate && <button onClick={()=>setCreate(true)} className="btn-primary text-sm"><Plus size={16} className="inline mr-1"/>Tạo Chiến dịch</button>}</div>{open && <div className="border-t divide-y">{campaigns.map(c=><div key={c.id} className="p-4 grid grid-cols-[1fr_auto] gap-3"><div><b>{c.name}</b><p className="text-sm text-gray-500 mt-1">{c.objective || 'Chưa có mục tiêu'}</p></div><div className="text-right text-xs text-gray-500"><span className="block capitalize text-primary font-semibold">{c.status}</span>{c.lead?.name || 'Chưa có lead'}</div></div>)}{!campaigns.length && <p className="p-6 text-center text-sm text-gray-400">Chưa có Campaign.</p>}</div>}<Modal isOpen={create} onClose={()=>setCreate(false)} title="Tạo Chiến dịch"><form onSubmit={save} className="space-y-4"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Tên chiến dịch" className="input-hub w-full"/><textarea value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Mục tiêu / KPI" className="input-hub w-full min-h-24"/><div className="grid grid-cols-2 gap-3"><input type="date" value={start} onChange={e=>setStart(e.target.value)} className="input-hub"/><input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="input-hub"/></div><input type="number" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Ngân sách dự kiến" className="input-hub w-full"/><div className="flex flex-wrap gap-3 text-sm">{['Social Media','In-store','OOH','PR'].map(x=><label key={x}><input type="checkbox" checked={channels.includes(x)} onChange={()=>setChannels(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x])}/> {x}</label>)}</div><select value={lead} onChange={e=>setLead(e.target.value)} className="input-hub w-full"><option value="">Campaign Lead</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="input-hub w-full"><option value="draft">Draft</option><option value="planning">Planning</option><option value="active">Active</option></select><button className="btn-primary w-full">Tạo chiến dịch</button></form></Modal></section>;
};
