import React, { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { FolderKanban, MessageSquare, Plus, Users } from 'lucide-react';
import { supabase } from '../services/supabase';
import { useAuthStore } from '../store/authStore';
import { Modal } from '../components/common/Modal';

type Project = { id: string; name: string; description: string | null; status: string; start_date: string | null; due_date: string | null; priority: string; created_by: number | null };
type Person = { id: number; name: string; department_id: string | null };

const dateValue = (value: string) => value ? new Date(value).toLocaleDateString('vi-VN') : '—';

export const Projects: React.FC = () => {
  const profile = useAuthStore(s => s.profile);
  const canCreate = profile?.role === 'admin' || profile?.role === 'manager' || profile?.employment_level === 'Leader';
  const [projects, setProjects] = useState<Project[]>([]); const [people, setPeople] = useState<Person[]>([]);
  const [members, setMembers] = useState<Record<string, string[]>>({}); const [selected, setSelected] = useState<Project | null>(null);
  const [createOpen, setCreateOpen] = useState(false); const [title, setTitle] = useState(''); const [description, setDescription] = useState('');
  const [start, setStart] = useState(''); const [due, setDue] = useState(''); const [priority, setPriority] = useState('medium'); const [ownerIds, setOwnerIds] = useState<string[]>([]);
  const [subtasks, setSubtasks] = useState<any[]>([]); const [comments, setComments] = useState<any[]>([]); const [newSubtask, setNewSubtask] = useState(''); const [subtaskOwner, setSubtaskOwner] = useState(''); const [subtaskDue, setSubtaskDue] = useState(''); const [comment, setComment] = useState('');

  const visiblePeople = useMemo(() => (profile?.role === 'admin' || profile?.role === 'manager') ? people : people.filter(p => p.department_id === profile?.department_id), [people, profile]);
  const load = async () => {
    const [projectRes, peopleRes, memberRes] = await Promise.all([
      supabase.from('projects').select('*').order('created_at', { ascending: false }),
      supabase.from('users').select('id,name,department_id').eq('is_active', true).order('name'),
      supabase.from('project_members').select('project_id,user_id'),
    ]);
    if (projectRes.error) return toast.error('Không thể tải Project');
    setProjects(projectRes.data || []); setPeople(peopleRes.data || []);
    setMembers((memberRes.data || []).reduce((acc: Record<string, string[]>, item: any) => ({ ...acc, [item.project_id]: [...(acc[item.project_id] || []), String(item.user_id)] }), {}));
  };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!selected) return; (async () => { const [s, c] = await Promise.all([supabase.from('project_subtasks').select('*, assignee:assignee_id(name)').eq('project_id', selected.id).order('created_at'), supabase.from('project_comments').select('*, author:author_id(name)').eq('project_id', selected.id).order('created_at')]); setSubtasks(s.data || []); setComments(c.data || []); })(); }, [selected]);
  const createProject = async (e: React.FormEvent) => { e.preventDefault(); if (!title) return; const { data, error } = await supabase.from('projects').insert({ name: title, description, start_date: start || null, due_date: due || null, priority, status: 'active', workspace_id: '9000eae0-528c-47a2-b6f3-eba019d4edca', created_by: profile?.id || null }).select().single(); if (error || !data) return toast.error('Không thể tạo Project'); if (ownerIds.length) await supabase.from('project_members').insert(ownerIds.map(user_id => ({ project_id: data.id, user_id: Number(user_id) }))); setCreateOpen(false); setTitle(''); setDescription(''); setOwnerIds([]); load(); toast.success('Đã tạo Project'); };
  const addSubtask = async () => { if (!selected || !newSubtask) return; await supabase.from('project_subtasks').insert({ project_id: selected.id, title: newSubtask, assignee_id: subtaskOwner ? Number(subtaskOwner) : null, due_date: subtaskDue || null }); setNewSubtask(''); setSubtaskOwner(''); setSubtaskDue(''); setSelected({ ...selected }); };
  const addComment = async () => { if (!selected || !comment) return; await supabase.from('project_comments').insert({ project_id: selected.id, author_id: profile?.id || null, body: comment }); setComment(''); setSelected({ ...selected }); };
  return <div className="h-full overflow-auto p-1 space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2"><FolderKanban className="text-primary"/> Projects</h1><p className="text-sm text-gray-500 mt-1">Theo dõi project, PIC, subtask và trao đổi.</p></div>{canCreate && <button onClick={() => setCreateOpen(true)} className="btn-primary flex items-center gap-2"><Plus size={18}/> New Project</button>}</div><div className="card-hub rounded-2xl overflow-hidden"><table className="w-full text-left"><thead className="bg-gray-50 dark:bg-slate-800 text-xs uppercase text-gray-500"><tr><th className="p-4">Project</th><th>Owner</th><th>Dates</th><th>Priority</th><th>Status</th></tr></thead><tbody>{projects.map(project => <tr key={project.id} onClick={() => setSelected(project)} className="border-t border-gray-100 dark:border-slate-800 cursor-pointer hover:bg-primary/5"><td className="p-4"><b className="text-gray-900 dark:text-white">{project.name}</b><p className="text-xs text-gray-500 line-clamp-1 mt-1">{project.description || 'No description'}</p></td><td><div className="flex -space-x-2">{(members[project.id] || []).slice(0,4).map(id => <span key={id} className="w-7 h-7 rounded-full bg-primary/15 border-2 border-white dark:border-slate-900 grid place-items-center text-[10px] font-bold">{people.find(p => String(p.id) === id)?.name?.[0] || '?'}</span>)}</div></td><td className="text-sm text-gray-600 dark:text-gray-300">{dateValue(project.start_date || '')} – {dateValue(project.due_date || '')}</td><td><span className="px-2 py-1 rounded-full text-xs bg-amber-100 text-amber-700">{project.priority}</span></td><td className="text-sm text-primary font-medium">{project.status}</td></tr>)}</tbody></table>{!projects.length && <div className="p-12 text-center text-gray-500">Chưa có Project nào.</div>}</div>
  <Modal isOpen={createOpen} onClose={() => setCreateOpen(false)} title="Create New Project"><form onSubmit={createProject} className="space-y-4"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Project Title" className="input-hub w-full"/><label className="text-sm font-semibold">Owner / PIC</label><select multiple value={ownerIds} onChange={e=>setOwnerIds(Array.from(e.target.selectedOptions).map(o=>o.value))} className="input-hub w-full h-32">{visiblePeople.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input type="date" value={start} onChange={e=>setStart(e.target.value)} className="input-hub"/><input type="date" value={due} onChange={e=>setDue(e.target.value)} className="input-hub"/></div><select value={priority} onChange={e=>setPriority(e.target.value)} className="input-hub w-full"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" className="input-hub w-full min-h-28"/><button className="btn-primary w-full">Create Project</button></form></Modal>
  <Modal isOpen={!!selected} onClose={()=>setSelected(null)} title={selected?.name || 'Project'}>
    <div className="space-y-7">
      <div className="flex gap-2"><span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-blue-50 text-primary border border-blue-100">Project</span><span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-amber-50 text-amber-700">{selected?.priority || 'medium'} Priority</span></div>
      <div className="grid grid-cols-2 gap-3 p-4 rounded-2xl bg-slate-50 dark:bg-slate-900/50 border border-blue-100 dark:border-slate-700 text-sm"><div><p className="text-[10px] uppercase text-gray-400">Owners</p><div className="mt-1 font-semibold">{(members[selected?.id || ''] || []).map(id=>people.find(p=>String(p.id)===id)?.name).filter(Boolean).join(', ') || 'Unassigned'}</div></div><div><p className="text-[10px] uppercase text-gray-400">Timeline</p><div className="mt-1 font-semibold">{dateValue(selected?.start_date || '')} – {dateValue(selected?.due_date || '')}</div></div></div>
      <section><h3 className="font-bold text-sm mb-2">Description</h3><div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-900/50 border border-blue-100 dark:border-slate-700 text-sm text-gray-600 dark:text-gray-300">{selected?.description || 'No description yet.'}</div></section>
      <section><h3 className="font-bold text-sm flex gap-2 items-center mb-3"><Users size={16}/> Subtasks</h3><div className="space-y-2">{subtasks.map(s=><div key={s.id} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800 border border-gray-100 dark:border-slate-700 text-sm"><b>{s.title}</b><span className="ml-2 text-gray-500">{s.assignee?.name || 'Unassigned'} · {dateValue(s.due_date || '')}</span></div>)}</div>{canCreate && <div className="grid grid-cols-4 gap-2 mt-3"><input value={newSubtask} onChange={e=>setNewSubtask(e.target.value)} placeholder="New subtask" className="input-hub col-span-2"/><select value={subtaskOwner} onChange={e=>setSubtaskOwner(e.target.value)} className="input-hub"><option value="">PIC</option>{visiblePeople.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={addSubtask} className="btn-secondary">Add</button></div>}</section>
      <section><h3 className="font-bold text-sm flex gap-2 items-center mb-3"><MessageSquare size={16}/> Activity & Comments</h3><div className="space-y-2">{comments.map(c=><div key={c.id} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800 text-sm"><b>{c.author?.name || 'Member'}</b><p>{c.body}</p></div>)}</div><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Write a comment to the team..." className="input-hub w-full min-h-24 mt-3"/><button onClick={addComment} className="btn-primary mt-3">Send comment</button></section>
    </div>
  </Modal></div>;
};
